"""
AI Text Detector - Streamlit Application
CSE 881: Automated Classification of Human vs AI Postings
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

ALL_MODELS = [
    "CatBoost",
    "Random Forest",
    "Logistic Regression",
    "SVM",
    "Neural Network",
    "Custom Algorithm",
]

# TODO: replace with actual results after training
RESULTS_DF = pd.DataFrame(
    {
        "Model": ALL_MODELS,
        "Accuracy": [0.972, 0.958, 0.923, 0.941, 0.965, 0.887],
        "Precision": [0.968, 0.952, 0.918, 0.937, 0.961, 0.879],
        "Recall": [0.975, 0.963, 0.929, 0.944, 0.968, 0.894],
        "F1": [0.971, 0.957, 0.923, 0.940, 0.964, 0.886],
        "AUC": [0.994, 0.987, 0.971, 0.978, 0.991, 0.932],
    }
)

EXAMPLE_TEXTS = {
    "Job Postings": {
        "Human": (
            "Overview: About The Geneva Foundation\n"
            "The Geneva Foundation is a 501(c)(3) nonprofit established in 1993 "
            "with the mission to advance military medicine. We work alongside "
            "clinicians and scientists at military medical centers and clinics "
            "around the world. Our research covers a wide range of areas, from "
            "traumatic brain injury and infectious diseases to psychological health."
        ),
        "AI": (
            "We are a growing, innovation-focused company that leverages data science, "
            "machine learning, and modern software engineering practices to build trusted "
            "products and services used by millions of end users. Our organization is a "
            "well-established technology and analytics company that supports a wide range "
            "of commercial and public-sector clients. We emphasize rigorous data-driven "
            "decision making and invest heavily in scalable analytics platforms."
        ),
    },
    "Agricultural Listings": {
        "Human": (
            "We are a small family farm in rural Vermont, raising heritage breed "
            "chickens and growing mixed vegetables on 12 acres. My husband and I "
            "started this place in 2008 after he came back from his second tour. "
            "The farm has been good therapy for both of us. We sell at the Saturday "
            "market in Burlington and run a small CSA program."
        ),
        "AI": (
            "Nestled in the heart of California's rural landscape, the Reentry Farmer "
            "Project is a small, family-run homestead dedicated to therapeutic agriculture "
            "and social farming. Our mission is to support formerly incarcerated individuals "
            "as they reenter society through the healing power of working the land. We focus "
            "on urban rooftop gardening and hydroponics, providing not just fresh produce but "
            "also a sense of purpose and community."
        ),
    },
}


# Page Functions


def page_home():
    with st.sidebar:
        st.subheader("Project Info")
        st.caption("CSE 881 — Spring 2025")
        st.markdown(
            "Automated classification of human vs. AI-generated "
            "text across two domains: job postings and agricultural listings."
        )
        st.divider()
        st.markdown("**Datasets**")
        st.markdown("- Job Postings: ~2,000")
        st.markdown("- Agricultural: 790")
        st.markdown("**AI Sources:** 9 models")

    st.header("AI Text Detector")
    st.caption(
        "Classify human vs. AI-generated text across job postings and agricultural listings."
    )

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Text Samples", "2,800+")
    m2.metric("Datasets", "2")
    m3.metric("AI Sources", "9")
    m4.metric("Models Trained", "6+")

    st.divider()

    st.subheader("Pipeline")
    s1, s2, s3, s4 = st.columns(4)
    with s1:
        st.markdown("**1. Collect**")
        st.caption("Scrape real postings from Indeed & Care Farming Network.")
    with s2:
        st.markdown("**2. Generate**")
        st.caption("Produce AI text via Claude, ChatGPT, Gemini, Copilot & more.")
    with s3:
        st.markdown("**3. Preprocess**")
        st.caption("Clean, normalize, extract features with NLTK & TF-IDF.")
    with s4:
        st.markdown("**4. Classify**")
        st.caption("Train models and detect AI text in real time.")

    st.divider()

    col_left, col_right = st.columns(2, gap="large")

    with col_left:
        st.subheader("Job Postings Dataset")
        st.markdown("""
        ~2,000 data science job postings. Human entries scraped from Indeed;
        AI entries generated by **5 LLMs** (Claude, ChatGPT, Copilot, Gemini, Perplexity).

        Fields: title, location, salary, description, label, source.
        """)

    with col_right:
        st.subheader("Agricultural Listings Dataset")
        st.markdown("""
        790 farm & agricultural listings. Human entries scraped from the
        Care Farming Network; AI entries generated by **4 NVIDIA NIM models**.

        Fields: id, name, description, label, source model.
        """)


def page_detector():
    if "detector_text" not in st.session_state:
        st.session_state["detector_text"] = ""
    if "history" not in st.session_state:
        st.session_state["history"] = []

    with st.sidebar:
        st.subheader("Settings")
        domain = st.selectbox("Domain", ["Job Postings", "Agricultural Listings"])
        model_choice = st.selectbox("Model", ALL_MODELS)
        show_signals = st.toggle("Show detection signals", value=True)

        st.divider()

        st.subheader("Try an Example")
        st.caption("Load sample text into the editor.")
        examples = EXAMPLE_TEXTS[domain]
        if st.button("Load Human example", use_container_width=True):
            st.session_state["detector_text"] = examples["Human"]
            st.rerun()
        if st.button("Load AI example", use_container_width=True):
            st.session_state["detector_text"] = examples["AI"]
            st.rerun()

        if st.session_state["history"]:
            st.divider()
            st.subheader("History")
            for entry in reversed(st.session_state["history"][-5:]):
                verdict = "AI" if entry["is_ai"] else "Human"
                st.caption(f"{verdict} ({entry['confidence']:.0%}) — {entry['model']}")

    st.header("Live Detector")
    st.caption("Paste text below and classify it as human-written or AI-generated.")

    if domain == "Job Postings":
        tab_text, tab_fields = st.tabs(["Paste text", "Structured fields"])

        with tab_text:
            user_text = st.text_area(
                "Full posting text",
                height=220,
                placeholder="Paste the job posting here...",
                label_visibility="collapsed",
                value=st.session_state["detector_text"],
                key="text_input_paste",
            )

        with tab_fields:
            f1, f2 = st.columns(2)
            with f1:
                job_title = st.text_input("Title", placeholder="Senior Data Scientist")
                job_location = st.text_input("Location", placeholder="New York, NY")
            with f2:
                job_salary = st.text_input(
                    "Salary", placeholder="$120,000 - $150,000/yr"
                )
            job_summary = st.text_area(
                "Description", height=180, placeholder="Full job description..."
            )
    else:
        user_text = st.text_area(
            "Listing description",
            height=220,
            placeholder="Paste the agricultural listing here...",
            label_visibility="collapsed",
            value=st.session_state["detector_text"],
            key="text_input_ag",
        )

    classify_clicked = st.button("Classify", use_container_width=True)

    if classify_clicked:
        # TODO: replace with actual model inference
        is_ai = True
        confidence = 0.93
        # TODO: replace with actual feature scores
        signals = [
            ("Vocabulary diversity", 85),
            ("Sentence regularity", 72),
            ("N-gram pattern score", 91),
            ("Repetition index", 68),
        ]

        with st.status("Classifying text...", expanded=True) as status:
            st.write("Preprocessing text...")
            st.write(f"Running **{model_choice}** model...")
            st.write("Computing detection signals...")
            status.update(label="Classification complete", state="complete")

        label = "AI-Generated" if is_ai else "Human-Written"
        st.toast(f"Result: {label} ({confidence:.0%})", icon=":material/check_circle:")

        if is_ai:
            st.error(f"**{label}** — {confidence:.0%} confidence ({model_choice})")
        else:
            st.success(f"**{label}** — {confidence:.0%} confidence ({model_choice})")

        st.badge(
            label,
            icon=":material/smart_toy:" if is_ai else ":material/person:",
            color="red" if is_ai else "green",
        )

        st.session_state["history"].append(
            {
                "is_ai": is_ai,
                "label": label,
                "confidence": confidence,
                "model": model_choice,
            }
        )
        st.session_state["detector_text"] = ""

        if show_signals:
            st.divider()
            st.subheader("Detection Signals")
            for lbl, val in signals:
                st.progress(val, text=f"{lbl} — {val}%")

        st.divider()
        st.caption("Was this classification accurate?")
        st.feedback("thumbs", key="detector_feedback")


def page_performance():
    with st.sidebar:
        st.subheader("Filters")
        perf_dataset = st.selectbox(
            "Dataset", ["Job Postings", "Agricultural Listings", "Combined"]
        )
        st.divider()
        st.subheader("Models")
        selected_models = []
        for m in ALL_MODELS:
            if st.checkbox(m, value=True, key=f"perf_{m}"):
                selected_models.append(m)

    filtered_df = RESULTS_DF[RESULTS_DF["Model"].isin(selected_models)]

    st.header("Model Performance")
    st.caption(f"Evaluation on **{perf_dataset}** dataset.")

    if not selected_models:
        st.warning("Select at least one model in the sidebar.")
        return

    best_idx = filtered_df["Accuracy"].idxmax()
    best = filtered_df.loc[best_idx]

    b1, b2, b3, b4 = st.columns(4)
    b1.metric("Best Model", best["Model"])
    b2.metric("Accuracy", f"{best['Accuracy']:.1%}")
    b3.metric("F1 Score", f"{best['F1']:.3f}")
    b4.metric("AUC-ROC", f"{best['AUC']:.3f}")

    st.divider()

    st.subheader("All Models")
    metric_cols = ["Accuracy", "Precision", "Recall", "F1", "AUC"]
    st.dataframe(
        filtered_df.style.format({c: "{:.1%}" for c in metric_cols}).highlight_max(
            subset=metric_cols, color="#ff4b4b40"
        ),
        use_container_width=True,
        hide_index=True,
    )

    st.divider()

    st.subheader("Visual Comparison")
    tab_bar, tab_cm, tab_roc = st.tabs(["Metrics", "Confusion Matrices", "ROC Curves"])

    with tab_bar:
        chart_df = filtered_df.set_index("Model")[
            ["Accuracy", "Precision", "Recall", "F1"]
        ]
        st.bar_chart(
            chart_df, height=380, color=["#ff4b4b", "#ff6b6b", "#ff8a8a", "#ffaaaa"]
        )

    with tab_cm:
        # TODO: replace placeholder matrices with actual values after training
        all_cms = {
            "CatBoost": np.array([[195, 5], [8, 192]]),
            "Random Forest": np.array([[190, 10], [7, 193]]),
            "Logistic Regression": np.array([[183, 17], [14, 186]]),
            "SVM": np.array([[187, 13], [11, 189]]),
            "Neural Network": np.array([[193, 7], [6, 194]]),
            "Custom Algorithm": np.array([[175, 25], [20, 180]]),
        }
        labels = ["Human", "AI"]
        cms_to_show = {k: v for k, v in all_cms.items() if k in selected_models}

        cols = st.columns(min(len(cms_to_show), 3))
        for i, (name, cm) in enumerate(cms_to_show.items()):
            with cols[i % 3]:
                fig = px.imshow(
                    cm,
                    x=labels,
                    y=labels,
                    text_auto=True,
                    color_continuous_scale=[[0, "#262730"], [1, "#ff4b4b"]],
                    aspect="equal",
                )
                fig.update_layout(
                    title=dict(text=name, font=dict(size=14)),
                    xaxis_title="Predicted",
                    yaxis_title="Actual",
                    margin=dict(l=40, r=20, t=40, b=40),
                    height=280,
                    coloraxis_showscale=False,
                    paper_bgcolor="rgba(0,0,0,0)",
                    plot_bgcolor="rgba(0,0,0,0)",
                    font=dict(color="#fafafa"),
                )
                st.plotly_chart(fig, use_container_width=True)

    with tab_roc:
        # TODO: replace with actual FPR/TPR from trained models
        np.random.seed(42)
        fig = go.Figure()
        all_roc = {
            "CatBoost": 0.994,
            "Neural Network": 0.991,
            "Random Forest": 0.987,
            "SVM": 0.978,
            "Logistic Regression": 0.971,
            "Custom Algorithm": 0.932,
        }
        colors_map = dict(
            zip(
                all_roc.keys(),
                ["#ff4b4b", "#ff6b6b", "#ff8a8a", "#ffaaaa", "#ffcccc", "#996060"],
            )
        )
        for name, auc in all_roc.items():
            if name not in selected_models:
                continue
            n = 200
            fpr = np.sort(np.concatenate([[0], np.random.beta(0.5, 3, n), [1]]))
            power = np.log(1 - auc + 1e-9) / np.log(0.5)
            tpr = 1 - (1 - fpr) ** (1 / max(power, 0.1))
            tpr = np.clip(np.sort(tpr), 0, 1)
            tpr[0], tpr[-1] = 0.0, 1.0
            fig.add_trace(
                go.Scatter(
                    x=fpr,
                    y=tpr,
                    mode="lines",
                    name=f"{name} (AUC={auc:.3f})",
                    line=dict(color=colors_map[name], width=2),
                )
            )
        fig.add_trace(
            go.Scatter(
                x=[0, 1],
                y=[0, 1],
                mode="lines",
                name="Random",
                line=dict(color="#555", width=1, dash="dash"),
                showlegend=False,
            )
        )
        fig.update_layout(
            xaxis_title="False Positive Rate",
            yaxis_title="True Positive Rate",
            legend=dict(x=0.55, y=0.05, bgcolor="rgba(0,0,0,0)"),
            margin=dict(l=40, r=20, t=20, b=40),
            height=420,
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            font=dict(color="#fafafa"),
            xaxis=dict(gridcolor="#333", zeroline=False),
            yaxis=dict(gridcolor="#333", zeroline=False),
        )
        st.plotly_chart(fig, use_container_width=True)

    st.divider()

    st.subheader("Cross-Dataset Generalization")
    cross_df = pd.DataFrame(
        {
            "Train": ["Jobs", "Jobs", "Agriculture", "Agriculture"],
            "Test": ["Jobs", "Agriculture", "Agriculture", "Jobs"],
            "CatBoost": ["97.2%", "81.4%", "95.6%", "78.3%"],
            "Random Forest": ["95.8%", "79.1%", "93.2%", "76.8%"],
            "Neural Net": ["96.5%", "83.7%", "94.8%", "80.1%"],
        }
    )
    st.dataframe(cross_df, use_container_width=True, hide_index=True)


def page_data():
    with st.sidebar:
        st.subheader("Filters")
        ds = st.selectbox("Dataset", ["Job Postings", "Agricultural Listings"])
        st.divider()

        if ds == "Job Postings":
            label_f = st.multiselect("Label", ["Human", "AI"], default=["Human", "AI"])
            source_f = st.multiselect(
                "Source",
                [
                    "human",
                    "chatgpt ai",
                    "claude ai",
                    "copilot ai",
                    "gemini ai",
                    "perplexity ai",
                ],
                default=[
                    "human",
                    "chatgpt ai",
                    "claude ai",
                    "copilot ai",
                    "gemini ai",
                    "perplexity ai",
                ],
            )
            max_rows = st.slider("Max rows", 10, 500, 100)
        else:
            label_f = st.multiselect(
                "Label", ["Human", "AI"], default=["Human", "AI"], key="ag_label"
            )
            model_f = st.multiselect(
                "AI Model",
                ["gpt-oss-120b", "glm-5", "gemma-3-1b-it", "qwen2.5-7b-instruct"],
                default=[
                    "gpt-oss-120b",
                    "glm-5",
                    "gemma-3-1b-it",
                    "qwen2.5-7b-instruct",
                ],
            )
            max_rows = st.slider("Max rows", 10, 500, 100, key="ag_rows")

    st.header("Dataset Explorer")
    st.caption("Browse, filter, and inspect training data.")

    st.divider()

    if ds == "Job Postings":
        c1, c2, c3 = st.columns(3)
        c1.metric("Total", "~2,000")
        c2.metric("Human", "~1,000")
        c3.metric("AI", "~1,000")

        col_table, col_chart = st.columns([3, 2], gap="large")

        with col_table:
            st.subheader("Sources")
            src_df = pd.DataFrame(
                {
                    "Source": [
                        "Human (Indeed)",
                        "ChatGPT",
                        "Claude",
                        "Copilot",
                        "Gemini",
                        "Perplexity",
                    ],
                    "Count": ["~1,000", "~200", "~200", "~200", "~200", "~200"],
                }
            )
            st.dataframe(src_df, use_container_width=True, hide_index=True)

        with col_chart:
            st.subheader("Distribution")
            chart_src = pd.DataFrame(
                {
                    "Source": [
                        "Human",
                        "ChatGPT",
                        "Claude",
                        "Copilot",
                        "Gemini",
                        "Perplexity",
                    ],
                    "Entries": [1000, 200, 200, 200, 200, 200],
                }
            ).set_index("Source")
            st.bar_chart(chart_src, height=250, color="#ff4b4b")

        st.divider()

        st.subheader("Sample Data")
        st.caption(
            f"Showing: labels={label_f}, sources={source_f}, limit={max_rows}"
        )
        # TODO: load from combined.csv with sidebar filters applied
        st.info("Connect `combined.csv` to display filtered data here.")

        with st.expander("Schema"):
            st.markdown("""
| Field | Type | Description |
|---|---|---|
| `job_title` | str | Title of the posting |
| `job_location` | str | City, State (normalized) |
| `job_salary` | str | Annual salary range |
| `job_summary` | str | Full description |
| `is_AI` | int | 0 = Human, 1 = AI |
| `source` | str | Origin of the entry |
            """)

    else:
        c1, c2, c3 = st.columns(3)
        c1.metric("Total", "790")
        c2.metric("Human", "390")
        c3.metric("AI", "400")

        col_table, col_chart = st.columns([3, 2], gap="large")

        with col_table:
            st.subheader("AI Models Used")
            ai_df = pd.DataFrame(
                {
                    "Model": [
                        "gpt-oss-120b",
                        "glm-5",
                        "gemma-3-1b-it",
                        "qwen2.5-7b-instruct",
                    ],
                    "Entries": [100, 100, 100, 100],
                }
            )
            st.dataframe(ai_df, use_container_width=True, hide_index=True)

        with col_chart:
            st.subheader("Distribution")
            ag_chart = pd.DataFrame(
                {
                    "Source": ["Human", "gpt-oss", "glm-5", "gemma-3", "qwen2.5"],
                    "Entries": [390, 100, 100, 100, 100],
                }
            ).set_index("Source")
            st.bar_chart(ag_chart, height=250, color="#ff4b4b")

        st.divider()

        st.subheader("Sample Data")
        st.caption(f"Showing: labels={label_f}, models={model_f}, limit={max_rows}")
        # TODO: load from scraping/*.json with sidebar filters applied
        st.info("Connect JSON files to display data here.")

        with st.expander("Schema"):
            st.markdown("""
| Field | Type | Description |
|---|---|---|
| `id` | str | URL-friendly slug |
| `name` | str | Listing name |
| `description` | str | Full description |
| `label` | str | Human or AI |
| `source_model` | str | Generation model (AI only) |
            """)

    st.divider()

    st.subheader("Text Statistics")
    ts1, ts2, ts3, ts4 = st.columns(4)
    ts1.metric("Avg Words (Human)", "147")
    ts2.metric("Avg Words (AI)", "183")
    ts3.metric("Avg Sent. Len (Human)", "18.2")
    ts4.metric("Avg Sent. Len (AI)", "22.7")


def page_about():
    with st.sidebar:
        st.subheader("Links")
        st.caption("CSE 881 — Spring 2025")
        st.markdown("**Team size:** 4")

    st.header("About")
    st.caption("Automated Classification of Human vs AI Postings — CSE 881")

    st.markdown("""
    This project develops a system to classify and detect AI-generated text across online
    postings. We scrape real human data from job boards and farming directories, generate
    synthetic AI text from multiple LLMs, then train and evaluate a suite of classifiers.
    """)

    st.divider()

    st.subheader("Methodology")
    tab_collect, tab_preprocess, tab_models, tab_eval = st.tabs(
        [
            "Collection",
            "Preprocessing",
            "Models",
            "Evaluation",
        ]
    )

    with tab_collect:
        st.markdown("""
**Job postings** — ~1,000 real postings scraped from Indeed via Octoparse.
~1,000 AI postings generated across Claude, ChatGPT, Copilot, Gemini, and Perplexity.

**Agricultural listings** — 390 real listings scraped from the Care Farming Network
using Playwright + BeautifulSoup. 400 AI listings generated via 4 NVIDIA NIM models.
        """)

    with tab_preprocess:
        st.markdown("""
- HTML / noise removal, markdown stripping
- Salary normalization (hourly to annual), location formatting (City, State)
- Stopword removal, lowercasing, n-gram extraction (NLTK)
- Binary encoding (Human = 0, AI = 1)
- 80 / 10 / 10 stratified train / validation / test split
        """)

    with tab_models:
        model_df = pd.DataFrame(
            {
                "Model": [
                    "Logistic Regression",
                    "Random Forest",
                    "SVM",
                    "CatBoost",
                    "Neural Network",
                    "Custom Algorithm",
                ],
                "Category": [
                    "Baseline",
                    "Baseline",
                    "Baseline",
                    "Gradient Boosting",
                    "Deep Learning",
                    "Hand-crafted",
                ],
                "Description": [
                    "Linear classifier on TF-IDF features",
                    "Ensemble of decision trees",
                    "SVM with RBF kernel",
                    "Handles categorical features natively",
                    "Multi-layer network on text embeddings",
                    "Rule-based AI writing pattern detection",
                ],
            }
        )
        st.dataframe(model_df, use_container_width=True, hide_index=True)

    with tab_eval:
        st.markdown("""
- Accuracy, precision, recall, F1, and AUC-ROC
- Cross-dataset evaluation (train on one domain, test on the other)
- Baseline vs. custom algorithm comparison
        """)

    st.divider()

    st.subheader("Team")
    t1, t2, t3, t4 = st.columns(4)
    with t1:
        st.markdown("**Hussain Aljafer**")
        st.caption(
            "Data collection, preprocessing, baseline models, AI detection algorithm"
        )
    with t2:
        st.markdown("**Wahid Hashem**")
        st.caption(
            "AI data generation, preprocessing, Streamlit app design & development"
        )
    with t3:
        st.markdown("**Aryan Sharma**")
        st.caption("AI data generation, baseline model research, evaluation, report")
    with t4:
        st.markdown("**Ricky Li**")
        st.caption("Agricultural scraping & generation, neural networks, evaluation")

    st.divider()

    st.subheader("Tech Stack")
    st.markdown("""
| Layer | Tools |
|---|---|
| Data & ML | Python, pandas, NumPy, scikit-learn, CatBoost, NLTK |
| Deep Learning | PyTorch / TensorFlow, text embeddings |
| Frontend | Streamlit, Plotly, Matplotlib |
| Scraping | Octoparse, Playwright, BeautifulSoup |
    """)


# Configure Streamlit App

st.set_page_config(
    page_title="AI Text Detector",
    layout="wide",
)

nav = st.navigation(
    [
        st.Page(page_home, title="Home", icon=":material/home:", url_path="home", default=True),
        st.Page(page_detector, title="Detector", icon=":material/search:", url_path="detector"),
        st.Page(page_performance, title="Performance", icon=":material/analytics:", url_path="performance"),
        st.Page(page_data, title="Data", icon=":material/database:", url_path="data"),
        st.Page(page_about, title="About", icon=":material/info:", url_path="about"),
    ],
    position="top",
)

nav.run()
